# Generated by Django 3.0.1 on 2019-12-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('os', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('lte_exists', models.NullBooleanField()),
                ('sim_count', models.IntegerField()),
                ('display', models.CharField(max_length=100)),
                ('memory_count', models.CharField(max_length=100)),
                ('bluetooth', models.NullBooleanField()),
                ('color', models.CharField(max_length=100)),
                ('screen_security', models.CharField(max_length=100)),
                ('dictofon', models.NullBooleanField()),
            ],
            options={
                'verbose_name': 'Iphone',
                'verbose_name_plural': 'Iphones',
                'db_table': 'iphone',
            },
        ),
        migrations.CreateModel(
            name='Samsung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('os', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('lte_exists', models.NullBooleanField()),
                ('sim_count', models.IntegerField()),
                ('display', models.CharField(max_length=100)),
                ('memory_count', models.CharField(max_length=100)),
                ('bluetooth', models.NullBooleanField()),
                ('color', models.CharField(max_length=100)),
                ('micro_sd', models.NullBooleanField()),
                ('micro_sd_memory', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Samsung',
                'verbose_name_plural': 'Samsungs',
                'db_table': 'samsung',
            },
        ),
        migrations.CreateModel(
            name='Xiaomi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('os', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('lte_exists', models.NullBooleanField()),
                ('sim_count', models.IntegerField()),
                ('display', models.CharField(max_length=100)),
                ('memory_count', models.CharField(max_length=100)),
                ('bluetooth', models.NullBooleanField()),
                ('color', models.CharField(max_length=100)),
                ('monobrov', models.NullBooleanField()),
            ],
            options={
                'verbose_name': 'Xiaomi',
                'verbose_name_plural': 'Xiaomis',
                'db_table': 'xiaomi',
            },
        ),
    ]
