# Generated by Django 2.1.1 on 2019-12-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20191221_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
        migrations.AlterModelTable(
            name='phone',
            table='phones',
        ),
    ]
